from supabase import create_client, Client
import os

SUPABASE_URL = "https://pouvubkqqagqprfkiwqs.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvdXZ1YmtxcWFncXByZmtpd3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MDc1NjgsImV4cCI6MjA4NzE4MzU2OH0.JKAqsMAqq4lZdpIfPXoLEf-CcMNJyPvuty0pDRuW3Zw"

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)